### ISSUE TITLE
Implement automatic reconnection for dropped connections

### ISSUE THREAD

**Issue by parfenovvs** [Malwarebytes/mbvpn-linux#31]
## Summary
Add automatic reconnection logic to handle dropped VPN connections and maintain persistent connectivity.

## Problem
Currently, if a VPN connection drops due to network issues, users must manually reconnect, leading to potential security gaps.

## Proposed Solution
Implement connection monitoring and automatic reconnection:

### Features
- Background monitoring of connection health
- Configurable retry attempts and intervals
- Exponential backoff for failed reconnections
- User notification of reconnection attempts
- Option to disable auto-reconnect

### Configuration Options
```yaml
# In ~/.config/mbvpn/config.yml
auto_reconnect:
  enabled: true
  max_attempts: 5
  initial_delay: 5s
  max_delay: 60s
  health_check_interval: 30s
```

### Command Line Options
```bash
# Enable auto-reconnect for this session
mbvpn connect us-east-01 --auto-reconnect

# Disable auto-reconnect
mbvpn connect us-east-01 --no-auto-reconnect

# Check auto-reconnect status
mbvpn status --reconnect-info
```

## Implementation Details
- Monitor WireGuard interface status
- Perform periodic connectivity tests
- Maintain connection state in background
- Handle network interface changes gracefully
- Log reconnection attempts for troubleshooting

## Priority
🎯 Priority 1 (1-2 weeks)

## Labels
- enhancement
- priority-1
- reliability
- networking
